[package]
name = "rustnabi"
version = "0.1.0"
authors = ["aaron"]

[dependencies]
chrono = "*"
ws = "*"
dotenv = "*"
pretty_env_logger = "*"
log = "*"
postgres = "*"
diesel = { version = "*", features = ["postgres", "serde_json", "network-address", "chrono"] }
ipnetwork = "*" # IP address type that Diesel uses
diesel-derive-enum = { version = "*", features = ["postgres"] }
serde_json = "*"
ring = "*"
lazy_static= "*" # for using a global RNG, as recommended in `ring` docs
